version: '3.9'
services:
    satisfactory:
        build:
          dockerfile: Dockerfile
        ports:
            - 7777:7777/udp
            - 15000:15000/udp
            - 15777:15777/udp
        volumes:
            # - /volume5/docker/satisfactory/config:/config
            - ./config:/config
        # platform: linux/amd64
        environment:
            - MAXPLAYERS=4
            - PGID=100
            - PUID=1026
            - STEAMBETA=false
            - AUTOPAUSE=false
            - AUTOSAVEINTERVAL=300
            - TZ=Asia/Seoul
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 30G
            reservations:
              memory: 16G